package br.edu.ifpe.sistemaeditais.model;

public enum AreaTematica {
    CIENCIAS_EXATAS_E_DA_TERRA,
    CIENCIAS_BIOLOGICAS,
    ENGENHARIAS,
    CIENCIAS_DA_SAUDE,
    CIENCIAS_AGRARIAS,
    CIENCIAS_SOCIAIS_APLICADAS,
    CIENCIAS_HUMANAS,
    LINGUISTICA_LETRAS_E_ARTES,
    MULTIDISCIPLINAR
}